
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _authenticate
        {
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION pass;
            WS_FIELD_DESCRIPTION* _authenticateFields [2]; 
        } _authenticatedescs; // end of _authenticate
        struct  // _authenticateResponse
        {
            WS_FIELD_DESCRIPTION authenticateResult;
            WS_FIELD_DESCRIPTION* _authenticateResponseFields [1]; 
        } _authenticateResponsedescs; // end of _authenticateResponse
    } globalElements;  // end of global elements
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _authenticateTypeName;  // authenticate
            WS_XML_STRING _authenticateTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _authenticateuserLocalName;  // user
            WS_XML_STRING _authenticatepassLocalName;  // pass
            WS_XML_STRING _authenticateResponseTypeName;  // authenticateResponse
            WS_XML_STRING _authenticateResponseauthenticateResultLocalName;  // authenticateResult
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {  // _authenticate
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateuserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_authenticate, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for pass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticatepassLocalName, // pass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_authenticate, pass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for pass
            {  // fields description for _authenticate
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._authenticatedescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._authenticatedescs.pass,
            },
        },    // _authenticate
        {  // _authenticateResponse
            {  // field description for authenticateResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateResponseauthenticateResultLocalName, // authenticateResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_authenticateResponse, authenticateResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for authenticateResult
            {  // fields description for _authenticateResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._authenticateResponsedescs.authenticateResult,
            },
        },    // _authenticateResponse
    }, // end of global elements
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("authenticate",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("user",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("pass",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("authenticateResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("authenticateResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
        },  // end of xmlStrings
        
        {  // tempuri_org_xsddictionary
          // 71ad58f9-1e30-4071-9671-6266d7fbb584 
        { 0x71ad58f9, 0x1e30, 0x4071, { 0x96, 0x71, 0x62,0x66, 0xd7, 0xfb, 0xb5, 0x84 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        6,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeName, // authenticate
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.authenticate,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateResponseTypeName, // authenticateResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.authenticateResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_authenticate),
        __alignof(_authenticate),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._authenticatedescs._authenticateFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._authenticatedescs._authenticateFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeName, // authenticate
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _authenticate
        {
        sizeof(_authenticateResponse),
        __alignof(_authenticateResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._authenticateResponsedescs._authenticateResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._authenticateResponsedescs._authenticateResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateResponseTypeName, // authenticateResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._authenticateTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _authenticateResponse
    },  // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
